### ISSUE TITLE
Segmentation Fault on running HelloWorld

### ISSUE THREAD

**Issue by raunaqbhirangi** [ATLFlight/ATLFlightDocs#10]
I am getting the following error when I try to run the HelloWorld programme. I tried building with both methods.

Asking DSP to say hello
/media/intrinsyc/BigDrive/Project/APQ8074Flight/LNX.LER.1.0-68037/APQ8074Flight/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:136:failed to create tls key/media/intrinsyc/BigDrive/Project/APQ8074Flight/LNX.LER.1.0-68037/APQ8074Flight/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:112:listener using ion heap: -1
Segmentation fault

**Comment by mcharleb** [comment]
What (if anything) do you see on the mini-dm output? What is in the target /lib/firmware directory? Please do "ls -l /lib/firmware" on the target

**Comment by raunaqbhirangi** [comment]
I get the same error when I try to run the DSPAL test. I had no problems compiling this one either.
Mini-dm Output:
[08500/03]  45:12.327  HAP:32820::error: -1: 0 != atomic_CompareAndExchange(&th->pgrp->bRunning, 1, 1)   0707  fastrpc_dsp_process_group.c
[08500/03]  45:12.327  HAP:32820:apps_std_flen failed ./libexample_interface_skel.so  0145  load.c
[08500/03]  45:12.327  HAP:28722::error: -1: me->pgrp->bRunning   0332  fastrpc_dsp_process_group.c
[08500/03]  45:12.327  HAP:32820::error: -1: 0 != atomic_CompareAndExchange(&th->pgrp->bRunning, 1, 1)   0704  fastrpc_dsp_process_group.c
[08500/03]  45:12.328  HAP:32820::error: -1: me->pgrp->bRunning   0332  fastrpc_dsp_process_group.c
[08500/03]  45:12.328  HAP:32820::error: -1: me->uRefs != 0   0119  pls.h
[08500/03]  45:12.328  HAP:32820::error: -1: 0 == pls_add_lookup_singleton(&th->pgrp->pls, type, key, size, ctor, ctx, dtor, ppo)   0575  fastrpc_dsp_process_group.c
[08500/03]  45:12.328  HAP:32820::error: -1: me->uRefs != 0   0119  pls.h
[08500/03]  45:12.328  HAP:32820::error: -1: 0 == pls_add_lookup_singleton(&th->pgrp->pls, type, key, size, ctor, ctx, dtor, ppo)   0575  fastrpc_dsp_process_group.c

And these are the contents of the /lib/firmware directory
-rwxr-xr-x 1 root root   1156 Dec 17 22:15 a225_pfp.fw
-rwxr-xr-x 1 root root   9220 Dec 17 22:15 a225_pm4.fw
-rwxr-xr-x 1 root root   9220 Dec 17 22:15 a225p5_pm4.fw
-rwxr-xr-x 1 root root   1156 Dec 17 22:15 a300_pfp.fw
-rwxr-xr-x 1 root root   9220 Dec 17 22:15 a300_pm4.fw
-rwxr-xr-x 1 root root   2212 Dec 17 22:15 a330_pfp.fw
-rwxr-xr-x 1 root root   9220 Dec 17 22:15 a330_pm4.fw
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b00 -> /firmware/image/adsp.b00
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b01 -> /firmware/image/adsp.b01
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b02 -> /firmware/image/adsp.b02
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b03 -> /firmware/image/adsp.b03
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b04 -> /firmware/image/adsp.b04
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b05 -> /firmware/image/adsp.b05
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b06 -> /firmware/image/adsp.b06
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b07 -> /firmware/image/adsp.b07
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b08 -> /firmware/image/adsp.b08
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b09 -> /firmware/image/adsp.b09
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b10 -> /firmware/image/adsp.b10
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b11 -> /firmware/image/adsp.b11
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.b12 -> /firmware/image/adsp.b12
lrwxrwxrwx 1 root root     24 Jan  1  1970 adsp.mdt -> /firmware/image/adsp.mdt
drwxr-xr-x 3 root root   4096 Dec 17 21:51 ar3k
drwxr-xr-x 3 root root   4096 Dec 17 21:50 ath6k
-rw-r--r-- 1 root root  16128 Dec 17 22:23 cpp_firmware_v1_1_1.fw
-rw-r--r-- 1 root root  16384 Dec 17 22:23 cpp_firmware_v1_1_6.fw
-rw-r--r-- 1 root root  16384 Dec 17 22:23 cpp_firmware_v1_2_0.fw
-rwxr-xr-x 1 root root   1156 Dec 17 22:15 leia_pfp_470.fw
-rwxr-xr-x 1 root root   9220 Dec 17 22:15 leia_pm4_470.fw
drwx------ 2 root root   4096 Jan  1  1970 lost+found
-rwxr-xr-x 1 root root    212 Dec 17 21:50 venus.b00
-rwxr-xr-x 1 root root    200 Dec 17 21:50 venus.b01
-rwxr-xr-x 1 root root 951376 Dec 17 21:50 venus.b02
-rwxr-xr-x 1 root root   5472 Dec 17 21:50 venus.b03
-rwxr-xr-x 1 root root     32 Dec 17 21:50 venus.b04
-rwxr-xr-x 1 root root 965072 Dec 17 21:50 venus.mbn
-rwxr-xr-x 1 root root    412 Dec 17 21:50 venus.mdt
-rwxr-xr-x 1 root root   1156 Dec 17 22:15 yamato_pfp.fw
-rwxr-xr-x 1 root root   9220 Dec 17 22:15 yamato_pm4.fw

**Comment by mcharleb** [comment]
@jywilson does this error look familiar? Old aDSP image?

**Comment by rkintada** [comment]
Yes.  This looks like old dsp image.  Can you please update the dsp image
with the sdk_addon that is provided in

http://support.intrinsyc.com/attachments/download/453/qcom_flight_controller_hexagon_sdk_add_on_for_Flight_3.0.zip

Thanks
Ramakrishna Kintada

**Comment by raunaqbhirangi** [comment]
I updated the dsp image. I ran these commands-
adb root
adb wait-for-device
adb remount
adb push ${HEXAGON_SDK_ROOT}\images\8074-eagle\normal\adsp_proc\obj\qdsp6v5_ReleaseG\LA\system\etc\firmware /lib/firmware
adb shell sync
adb reboot

I compiled the program again and tried running it. I got the following error(s):

Asking DSP to say hello
/media/intrinsyc/BigDrive/Project/APQ8074Flight/LNX.LER.1.0-68037/APQ8074Flight/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:136:failed to create tls key/media/intrinsyc/BigDrive/Project/APQ8074Flight/LNX.LER.1.0-68037/APQ8074Flight/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:112:listener using ion heap: -1
/media/intrinsyc/BigDrive/Project/APQ8074Flight/LNX.LER.1.0-68037/APQ8074Flight/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:129:listener protocol failure -1
/media/intrinsyc/BigDrive/Project/APQ8074Flight/LNX.LER.1.0-68037/APQ8074Flight/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:133::error: -1: 0 == (nErr = __QAIC_HEADER(adsp_listener_next_invoke)( ctx, nErr, 0, 0, &ctx, &handle, &sc, bufs->inbufs, inBufsAllocated, bufs->inbufLenReqs, MAX_BUFS, bufs->outbufLenReqs, MAX_BUFS))
/media/intrinsyc/BigDrive/Project/APQ8074Flight/LNX.LER.1.0-68037/APQ8074Flight/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:192:listener thread exiting with code -1
/media/intrinsyc/BigDrive/Project/APQ8074Flight/LNX.LER.1.0-68037/APQ8074Flight/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:194:listener thread failed to cleanly shutdown.  This is ok durring process exit.
/media/intrinsyc/BigDrive/Project/APQ8074Flight/LNX.LER.1.0-68037/APQ8074Flight/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:159:exit: closing /dev/adsprpc-smd, rpc errors are expected.

mini-dm output is just this
[08500/00]  07:44.653  HAP:8237:Hello World  0037  helloworld_dsp.c

**Comment by rkintada** [comment]
Hi Raunaq,

The output looks good.  The messages from adsprpc are ok and can be
ignored.  The mini-dm output confirms that the module loaded and printed
Hello World.

Thanks
Rama
