### ISSUE TITLE
apt-get fix instructions don't work

### ISSUE THREAD

**Issue by Seanmatthews** [ATLFlight/ATLFlightDocs#21]
https://github.com/ATLFlight/ATLFlightDocs/blob/master/TroubleshootFAQ.md#apt-get-does-not-work

on `dpkg -i fastcv-internal_1.0-r0_armhf.deb`:

> (Reading database ... 51118 files and directories currently installed.)
> Preparing to unpack fastcv-internal_1.0-r0_armhf.deb ...
> Unpacking fastcv-internal (1.0-r0) over (1.0-r0) ...
> dpkg: dependency problems prevent configuration of fastcv-internal:
>  fastcv-internal depends on fastcv-noship (>= 1.0); however:
>   Package fastcv-noship is not installed.
> 
> dpkg: error processing package fastcv-internal (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  fastcv-internal

**Comment by rkintada** [comment]
Were you able to run the command "apt-get install -f"?  If this already done, then there is not need to reinstall the package.  Is there a reason you are trying to install it them?

Also we update the documentation to remove the additional instructions.

Thanks
Ramakrishna

**Comment by rkintada** [comment]
HI Sean, 

I need to check this failure.  For the test to pass, re-installing the packages is not needed.  Can you please run the "camera-test -i" on target and post the result.  This application should be part of the image already.

Also the test application seems to be incorrectly passing where it should have failed.  I will look into this.

Thanks
Rama

**Comment by Seanmatthews** [comment]
> camera-test -i
> num_cameras = 2
>  i = 0 , info.func = 1 
>  i = 1 , info.func = 0 
> Testing camera id=1
> [KPI Perf  840718351] openCamera: E PROFILE_OPEN_CAMERA camera id 1
> Camera capabilities
> available preview sizes:
> 0: 4208 x 3120
> 1: 4096 x 2160
> 2: 3840 x 2160
> 3: 2560 x 1440
> 4: 2104 x 1560
> 5: 1920 x 1080
> 6: 1280 x 720
> 7: 864 x 480
> 8: 800 x 480
> 9: 800 x 400
> 10: 768 x 432
> 11: 720 x 480
> 12: 640 x 480
> 13: 640 x 240
> 14: 1280 x 480
> 15: 576 x 432
> 16: 480 x 320
> 17: 384 x 288
> 18: 352 x 288
> 19: 320 x 240
> 20: 240 x 160
> 21: 176 x 144
> available video sizes:
> 0: 4208 x 3120
> 1: 4096 x 2160
> 2: 3840 x 2160
> 3: 2560 x 1440
> 4: 2104 x 1560
> 5: 1920 x 1080
> 6: 1280 x 720
> 7: 864 x 480
> 8: 800 x 480
> 9: 720 x 480
> 10: 640 x 480
> 11: 640 x 240
> 12: 1280 x 480
> 13: 480 x 320
> 14: 352 x 288
> 15: 320 x 240
> 16: 176 x 144
> available picture sizes:
> 0: 4208 x 3120
> 1: 4128 x 3096
> 2: 4128 x 2322
> 3: 4096 x 2160
> 4: 3840 x 2160
> 5: 4000 x 3000
> 6: 3200 x 2400
> 7: 2592 x 1944
> 8: 2104 x 1560
> 9: 2048 x 1536
> 10: 1920 x 1080
> 11: 1600 x 1200
> 12: 1280 x 768
> 13: 1280 x 720
> 14: 1024 x 768
> 15: 800 x 600
> 16: 864 x 480
> 17: 800 x 480
> 18: 720 x 480
> 19: 640 x 480
> 20: 640 x 240
> 21: 1280 x 480
> 22: 352 x 288
> 23: 320 x 240
> available preview formats:
> 0: yuv420sp
> 1: yuv420p
> 2: nv12-venus
> 3: bayer-rggb
> available focus modes:
> 0: auto
> 1: infinity
> 2: macro
> 3: continuous-video
> 4: continuous-picture
> 5: manual
> available whitebalance modes:
> 0: auto
> 1: incandescent
> 2: fluorescent
> 3: warm-fluorescent
> 4: daylight
> 5: cloudy-daylight
> 6: twilight
> 7: shade
> 8: manual-cct
> available ISO modes:
> 0: auto
> 1: ISO_HJR
> 2: ISO100
> 3: ISO200
> 4: ISO400
> 5: ISO800
> 6: ISO1600
> 7: ISO3200
> available brightness values:
> min=0, max=6, step=1
> available sharpness values:
> min=0, max=36, step=6
> available contrast values:
> min=0, max=10, step=1
> available preview fps ranges:
> 0: [15000, 15000]
> 1: [24000, 24000]
> 2: [30000, 30000]
> 3: [60000, 60000]
> 4: [90000, 90000]
> 5: [7500, 120000]
> 6: [120000, 120000]
> available video fps values:
> 0: 2
> 1: 3
> 2: 4
> 3: 1
>

**Comment by Seanmatthews** [comment]
I was trying to install them because that's what was specified in the instructions, and also because I thought it might have something to do with the referenced issue where `rosrun snap_ros_examples test_snap_cam_manager` does not work properly.

**Comment by rkintada** [comment]
Hi Sean. 
The camera test output looks good.  It may be an issue with the test app...I will look into this.

Regarding the document we will update it to not have the reinstall.

Thanks 
Rama

**Comment by Seanmatthews** [comment]
Thanks @rkintada. Did I miss a setup step somewhere? After some light debugging, it looks like startPreview() returns successfully, but onPreviewFrame() is never called. Could this be a permissions issue? 

My install steps FYI:
* Flashed 3.1.2 from Intrinsyc 
* [apt-get fix](https://github.com/ATLFlight/ATLFlightDocs/blob/master/TroubleshootFAQ.md#apt-get-does-not-work)
* [ROS Installation](https://github.com/ATLFlight/ATLFlightDocs/blob/master/SnapdragonROSInstallation.md)

**Comment by rkintada** [comment]
HI @Seanmatthews , looks like this is an issue with Camera not working based on date( after 4/1 ).  We are internally able to reproduce it and working on the issue.  We will keep you posted.  Here is the QDN issue link:
https://developer.qualcomm.com/forum/qdn-forums/hardware/snapdragon-flight/34148

We initially thought this was a april fools joke :-)  But apparently not.

**Comment by bharath374** [comment]
Hi @Seanmatthews , please check this post for a fix/workaround to the camera preview frame issue: 
https://developer.qualcomm.com/forum/qdn-forums/hardware/snapdragon-flight/34157

**Comment by Seanmatthews** [comment]
Camera issue solved with updated library files.
