### ISSUE TITLE
Document LA vs. non_reloc vs. unsigned 

### ISSUE THREAD

**Issue by julianoes** [ATLFlight/ATLFlightDocs#3]
The qcom_flight_controller_hexagon_sdk_add_on.zip contains different static image files:

```
images/8074-eagle/normal/adsp_proc/obj/qdsp6v5_ReleaseG
├── LA
│   └── system
│       └── etc
│           └── firmware
│               ├── ...
├── non_reloc
│   └── LA
│       └── system
│           └── etc
│               └── firmware
│                   ├── ...
└── unsigned
    ├── ...
```

It is not clear what each of them are for and which ones need to be flashed. I would propose only to include what is actually needed and working. I (as a stupid user) for instance ended up flashing the wrong ones because I was desperate and ended up loosing almost a week of development because it bricked my board.

**Comment by mcharleb** [comment]
@julianoes Future releases will not have the non_reloc directory tree

**Comment by julianoes** [comment]
ok thanks.
