### ISSUE TITLE
Setting up Snapdragon with Qualcomm ESC

### ISSUE THREAD

**Issue by msadowski** [ATLFlight/ATLFlightDocs#33]
[This](https://github.com/ATLFlight/ATLFlightDocs/blob/master/PX4.md#building-with-upstream-drivers) section of ALTFlight Documentation says

> To build code for this configuration, please SKIP the rest of this page and follow the instructions in the official PX4 documentation at http://dev.px4.io/starting-building.html.

However the PX4 documentation at the link above points back to ALTFlightDocs:

> If you use the Qualcomm ESC board, please follow their instructions [here](https://github.com/ATLFlight/ATLFlightDocs/blob/master/PX4.md).

I already know that one needs to build the PX4 with eagle_legacy_default. Is there anything else that needs to be changed while following PX4 docs to use Qualcomm ESC board?

**Comment by potaito** [comment]
Nope, that should do it for compiling the code. You'll also have to use the startup scripts from ATL, not px4 or it will not load the qualcomm ESC driver. That's done with the `adb push` commands in this section here:
https://github.com/ATLFlight/ATLFlightDocs/blob/master/PX4.md#installation-on-target

**Comment by msadowski** [comment]
Thanks for your help @potaito!
