### ISSUE TITLE
A note on executing arm-linux-gnueabihf-g** in Ubuntu 64 bit

### ISSUE THREAD

**Issue by alsaibie** [ATLFlight/ATLFlightDocs#4]
When: executing "make posix_eagle_default" 
What: Make error: arm-linux-gnueabihf-g++ not found even through path is set correctly
Why: Missing multi-architecture (64bit Host - 32bit binaries) compatibility. 
Fix: Install support through a combination of lib32stdc++6 lib32z1 lib32z1-dev gcc-multilib, then rerun cross_toolchain/install.sh

**Comment by mcharleb** [comment]
@alsaibie The Hexagon 3.0 SDK uses a gcc 4.9 cross compiler that is x86_64 native (not i386). This issue should not come up in the future. Thanks!
