### ISSUE TITLE
GPIO, open drain output

### ISSUE THREAD

**Issue by skye-AL** [ATLFlight/ATLFlightDocs#5]
@mcharleb @jywilson 

I was wondering whether the GPIO controller directly supports open drain outputs, or whether one needs to emulate this with first:
DSPAL_GPIO_DIRECTION_OUTPUT, DSPAL_GPIO_LOW_VALUE
and then 
DSPAL_GPIO_DIRECTION_INPUT, DSPAL_GPIO_PULL_DOWN/DSPAL_GPIO_NO_PULL
as described here: https://www.kernel.org/doc/Documentation/gpio/gpio-legacy.txt

because I couldn't find any setting in dspal/include/dev_fs_lib_gpio.h. Any suggestion?

**Comment by jywilson** [comment]
You are correct.  The GPIO controller does not have a single configuration option that would behave in the manner required for open drain output.  You have to emulate this behavior as you proposed above.

**Comment by skye-AL** [comment]
Good, thank you for your clarification. Nice to know that I did not do unnecessary coding just because of lack of understanding. And the emulation works neatly.
