### ISSUE TITLE
problem when make HelloWorld

### ISSUE THREAD

**Issue by nanfly** [ATLFlight/ATLFlightDocs#7]
When make in the HelloWorld directory, error comes up showing 

`arm-linux-gnueabihf-gcc: error: /home/nanfly/Qualcomm/Hexagon_SDK/2.0/lib/common/rpcmem/UbuntuARM_Debug/rpcmem.a: No such file or directory
`

Pull and run the latest croo-toolchain, every seems normal but the rpcmem.a is still not there.

Try directly generate the rpemem.a in the directory as indicated in the install.sh and error comes up as 

`nanfly@nanfly-XPS:~/Qualcomm/Hexagon_SDK/2.0/lib/common/rpcmem$ make V=UbuntuARM_Debug
../../../tools/make.d.ext/UbuntuARM/../../../gcc-linaro-arm-linux-gnueabihf-4.8-2013.08_linux/bin/arm-linux-gnueabihf-gcc -c -fPIC -Wall -Wno-missing-braces -mword-relocations -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a8 -march=armv7-a -Werror -g -isystem ../../../tools/make.d.ext/UbuntuARM/../../../gcc-linaro-arm-linux-gnueabihf-4.8-2013.08_linux/arm-linux-gnueabihf/libc/usr/include -DARM_ARCH_7A -DUSE_SYSLOG -std=gnu99      -D__FILENAME__=\"rpcmem_android.c\" -D_DEBUG  -I. -I../../../inc/a1std -I../../../inc/qlist -I../../../inc/stddef -IUbuntuARM_Debug  -oUbuntuARM_Debug/rpcmem_android.o rpcmem_android.c
make: ../../../tools/make.d.ext/UbuntuARM/../../../gcc-linaro-arm-linux-gnueabihf-4.8-2013.08_linux/bin/arm-linux-gnueabihf-gcc: Command not found
make: *** [UbuntuARM_Debug/rpcmem_android.o] Error 127`

I have been having this problem since I got the flight dragon board a few weeks ago and tried every time the source code on the github is updated. Can anyone help me finally solve this problem?

Thanks in advance.

**Comment by mcharleb** [comment]
Its trying to use a version of gcc that is not installed. It should be able to use ${HEXAGON_SDK_ROOT}/gcc-linaro-arm-linux-gnueabihf-4.8-2013.08_linux/bin/arm-linux-gnueabihf-gcc

Please run the following commands and list the output:
```
env | grep HEXAGON
echo $PATH
ls ~/Qualcomm/Hexagon_SDK/2.0
```

**Comment by nanfly** [comment]
@mcharleb `nanfly@nanfly-T440p:~$ env | grep HEXAGON
nanfly@nanfly-T440p:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
nanfly@nanfly-T440p:~$ ls ~/Qualcomm/Hexagon_SDK/2.0
docs                                              inc               sysroot
examples                                          lib               test
gcc-linaro-arm-linux-gnueabihf-4.8-2013.08_linux  readme.txt        tools
images                                            setup_sdk_env.sh
nanfly@nanfly-T440p:~$ 

`

**Comment by nanfly** [comment]
Problem solved. It is a 32/64 compatibility issue. I am working on a 64bit Ubuntu 14.04 and I guess some of the gcc package doesn't support 64bit. Anyway, I installed the package for 32bit compatibility and the HelloWorld works now.

For anyone that may encounter the same problem, the package I installed that solved the problem is:

`sudo dpkg --add-architecture i386`

Hope this helps.

**Comment by nanfly** [comment]
`sudo -i
cd /etc/apt/sources.list.d
echo "deb http://old-releases.ubuntu.com/ubuntu/ raring main restricted universe multiverse" >ia32-libs-raring.list
apt-get update
apt-get install ia32-libs`

**Comment by nanfly** [comment]
`sudo -i
cd /etc/apt/sources.list.d
echo "deb http://old-releases.ubuntu.com/ubuntu/ raring main restricted universe multiverse" >ia32-libs-raring.list
apt-get update
apt-get install ia32-libs`

**Comment by nanfly** [comment]
`sudo -i
cd /etc/apt/sources.list.d
echo "deb http://old-releases.ubuntu.com/ubuntu/ raring main restricted universe multiverse" >ia32-libs-raring.list
apt-get update
apt-get install ia32-libs
`

**Comment by mcharleb** [comment]
You don't have arm-linux-gnueabihf-gcc in your path
