### ISSUE TITLE
dspal_tester make error

### ISSUE THREAD

**Issue by nanfly** [ATLFlight/ATLFlightDocs#8]
When: following the instruction [(https://github.com/ATLFlight/dspal)]

What: 
```
nanfly@nanfly-T440p:~/dspal/test/dspal_tester$ ls
adsp_proc  cmake_hexagon   common            include
apps_proc  CMakeLists.txt  dspal_tester.idl  Makefile
nanfly@nanfly-T440p:~/dspal/test/dspal_tester$ make
make: *** No rule to make target `cmake_hexagon/toolchain/Toolchain-qurt.cmake, needed by `dspal_tester'.  Stop.
```

Why: Don't know. Can anyone help?

I am using the latest pull and can make the HelloWorld program with no problem.

Thanks in advance.

**Comment by mcharleb** [comment]
@nanfly Is there anything in your cmake_hexagon/toolchain directory?

**Comment by raunaqbhirangi** [comment]
I had the same error. My cmake_hexagon directory was empty when I cloned. I downloaded the contents separately and put them there. It compiled fine after that.

**Comment by mcharleb** [comment]
@nandfly @raunaqbhirangi After git clone of dspal, run:

    git submodule update --init --recursive

That will populate any submodules used.

**Comment by khoinguyen258** [comment]
Hi @raunaqbhirangi could you run make load function without error after make succesful?

**Comment by raunaqbhirangi** [comment]
@khoinguyen258 Yes I could.
