### ISSUE TITLE
could not load_bundle

### ISSUE THREAD

**Issue by khoinguyen258** [ATLFlight/ATLFlightDocs#9]
Hi all
I do exactly like the tutorial. but I can not   run "make load-bundle".
The terminal returns

ake[4]: Entering directory '/home/khoi/cross_toolchain/HelloWorld/bundle/build_bundle'
error: unknown host service
error: unknown host service
CMakeFiles/helloworld_app-load.dir/build.make:57: recipe for target 'CMakeFiles/helloworld_app-load' failed
make[4]: *** [CMakeFiles/helloworld_app-load] Error 1

How can I fix the host service?
Thank all

**Comment by khoinguyen258** [comment]
Hi all found some error in cmake file
Detecting CXX [-std=c++14] compiler features failed to compile with the following output:
Change Dir: /home/khoi/cross_toolchain/HelloWorld/bundle/build_bundle/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_e5015/fast"
make[1]: Entering directory '/home/khoi/cross_toolchain/HelloWorld/bundle/build_bundle/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_e5015.dir/build.make CMakeFiles/cmTC_e5015.dir/build
make[2]: Entering directory '/home/khoi/cross_toolchain/HelloWorld/bundle/build_bundle/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_e5015.dir/feature_tests.cxx.o
/home/khoi/Qualcomm/HEXAGON_Tools/7.2.12/Tools/bin/hexagon-clang++     -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -O0 -mv5 -G0    -D __QURT -D _PID_T -D _UID_T -D _TIMER_T -D _HAS_C9X -D restrict=__restrict__ -D noreturn_function= -std=c++14 -o CMakeFiles/cmTC_e5015.dir/feature_tests.cxx.o -c /home/khoi/cross_toolchain/HelloWorld/bundle/build_bundle/CMakeFiles/feature_tests.cxx
error: invalid value 'c++14' in '-std=c++14'
CMakeFiles/cmTC_e5015.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_e5015.dir/feature_tests.cxx.o' failed
make[2]: *** [CMakeFiles/cmTC_e5015.dir/feature_tests.cxx.o] Error 1
make[2]: Leaving directory '/home/khoi/cross_toolchain/HelloWorld/bundle/build_bundle/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_e5015/fast' failed
make[1]: *** [cmTC_e5015/fast] Error 2
make[1]: Leaving directory '/home/khoi/cross_toolchain/HelloWorld/bundle/build_bundle/CMakeFiles/CMakeTmp'

It looks like my std 14 and c++14 problem .Hope anyone can help

**Comment by mcharleb** [comment]
@khoinguyen258 Can you tell me what host Linux version you are running? If Ubuntu, can you tell me what version of GCC version you have? You should not be using -std=c++14 to build.

**Comment by khoinguyen258** [comment]
Hi . I fixed that problem.
at cmax hexagon, It would be adb wait for devices should be adb wait for device without 's'
@mcharleb
